config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
root "posts#index"
resources :posts
get 'locale', to: 'locales#save_locale', as: :set_locale

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
mount_uploader :picture, PictureUploader

    after_create :notify_admin

    def notify_admin
        PostsMailer.new_post_notification(self).deliver
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        I18n.locale = session[:locale] || I18n.default_locale
    end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
    def save_locale 
        session[:locale] = params[:locale]
        redirect_back fallback_location: root_path
        #redirect_to :back
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.page(params[:page]).per(3)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "dziękujemy za wpis"
      redirect_to posts_path
    end

  end

  private

  def post_params
    params.require(:post).permit(:autor, :body, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuestBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="page-header">
        <% if flash[:notice]%>
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <h1>Księga gości</h1>
        </div>
        <%= yield %>
      </div>  

      <div>
        <%= yield %>

        <% if user_signed_in? %>
        <p><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></p>
        <% end %>
      </div>
  </body>
</html>

app/views/posts/index.html.erb
<pre>
    <%= I18n.localize Time.now, format: :short%>
    <%= l Date.today, format: :short%>
    <%= number_to_currency 1254.444444444%>
    <%= number_with_delimiter(1123131232.1231231231)%>
    <%= distance_of_time_in_words(rand(10_000).seconds)%>
</pre>
<% if user_signed_in? %>
<p class="lead">
    <%= t "index.hello"%>
    <%= link_to "Dodaj własny wpis już teraz.", new_post_path%>
</p>
<% else %>

<p class="lead">
    Musisz się zalogować, aby dodać wpis.
    <%= link_to "Zaloguj się", new_user_session_path %>
</p>

<% end %>

<% @posts.each do |post|%>
    <div class="row">
        <div class="col-md-4">
            <%= image_tag post.picture.url(:thumb)%>
        </div>
    <div class="col-md-8">
    <blockquote>
        <p><%= post.body%></p>
        <footer><cite><%= post.autor %></cite></footer>
    </blockquote>
    </div>
    </div>
<% end %>

<div class="row">
    <div class="col-md-12">
    </div>
</div>

<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <%= t "index.select_language", language: I18n.locale %> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><%= link_to "PL", set_locale_path(locale: "pl")%></li>
        <li><%= link_to "EN", set_locale_path(locale: "en")%></li>
    </ul>
</div>
<br>
<%= paginate @posts%>

app/views/posts/new.html.erb
<h2>Dodawanie nowego wpisu</h2>
<%= simple_form_for @post do |f| %>
<%= f.input :autor, hint: "Podaj swoje imię" %>
<%= f.file_field :picture, label: "Obrazek"%> 
<%= f.input :body, label: "Treść", hint: "Treść" %> 
<%= f.submit class: "btn btn-default"%>


<% end %>